### ISSUE TITLE
Deployment process

### ISSUE THREAD

**Issue by xeho91** [Team-LogiDev/terminal-nerd#3]
This is the first step in deciding on our **deployment process**.

Where will we deploy our client _(website app)_ and server _(API)_?

**Comment by xeho91** [comment]
For the **client-side**, I recommend [Vercel](https://vercel.com). It offers a great developer's experience, by the automated and smooth deploying process.

**Comment by lax0248917** [comment]
Will we be housing a datastore locally? Or are we looking for a deployment process for a database? Something like MongoDB as an example

**Comment by xeho91** [comment]
I did research, and since we're not going to build a _"serverless"_ app, we need to host our API server outside localhost _(for the public display)_.

So, the one that I am familiar with, its free, has integration with GitHub, is [Heroku].

I recommend [Heroku] for the **server-side**.

[Heroku]: https://www.heroku.com/
